version: '3'
services:

  Patient:
    image: 'patient'
    build:
      context: ./application/Patient
      dockerfile: Dockerfile
    ports:
    - "8080:8080"

  Doctor:
    image: 'doctor'
    build:
      context: ./application/Doctor/doctor
      dockerfile: Dockerfile
    ports:
      - "8081:8081"

  Medicine:
    image: 'medication'
    build:
      context: ./application/Medication/medicine
      dockerfile: Dockerfile
    ports:
      - "8082:8082"


  Chatmicroservice:
    image: 'chatmicroservice'
    build:
      context: ./application/Chat/chatmicroservice
      dockerfile: Dockerfile
    ports:
      - "8089:8089"

    
  Adminmicroservice:
    image: 'adminmicroservice'
    build:
      context: ./application/Adminmicroservice
      dockerfile: Dockerfile
    ports:
      - "8083:8083"

  HealthInfo:
    image: 'healthinfo'
    build:
      context: ./application/HealthInformation/healthinformation
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
      
  Bookings:
    image: 'bookings'
    build:
      context: ./application/Bookings/bookings
      dockerfile: Dockerfile
    ports:
      - "8085:8085"

  Symptoms:
    image: 'symptomsmicroservice'
    build:
      context: ./application/Symptoms
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
